apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    name: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: app1
        image: deepaknautiyal/flask:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  labels:
    service: flaskapp-service
spec:
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flaskapp-ingress
  annotations:
spec:
  backend:
    serviceName: flaskapp-service
    servicePort: 5000